### ISSUE TITLE
Settings page crashes on phone number submitted

### ISSUE THREAD

**Issue by Kaffeine** [Kaffeine/sailfish-settings-accounts-extensions-telegram#2]
**Description**
Settings page crashes on phone number submitted.

**To Reproduce**
1. Open new account creation page
2. Enter custom phone number
3. Accept
4. See the crash

**Environment**
 - Device: Any
 - OS version: Any

**Additional context**
- A custom phone number (Italian)

**Comment by Kaffeine** [comment]
Log (with `QT_LOGGING_RULES="telegram.operations.debug=true"`)

```
[I] unknown:0 - Initialize TelegramQt v0.2.0 (build
0.2.0+next.staging.20190227142143.1133.g41e90ad)
[W] unknown:70 - file:///usr/lib/qt5/qml/com/jolla/settings/accounts
/AccountAgentRunner.qml:70:5: QML Connection
s: Cannot assign to non-existent property "onPageContainerChanged"
[D] unknown:0 - Telegram::Client::AuthOperation(0xabc711e0,
name = "Auth/StartAuthentication") runAfter( Telegram::PendingOperation(0xabc0b400,
name = "ConnectionApi::connectToServer(dcs from settings)") )
[D] unknown:0 - Telegram::Client::AuthOperation(0xabc711e0,
name = "Auth/StartAuthentication") start()
[W] unknown:0 - No connection for processMethod
[W] unknown:0 - QObject::connect: invalid null parameter
[D] unknown:0 - Telegram::Client::ConnectOperation(0xabc72a50, name = 
"ConnectTo(149.154.175.50:443)") start()
[D] unknown:0 - Telegram::Client::PendingRpcOperation(0xab4f8ba8, name = 
"RPC/ReqPq") setFinished(succeeded)
[D] unknown:0 - Telegram::Client::PendingRpcOperation(0xabc738a8, name = 
"RPC/ReqDHParams") setFinished(succeeded)
[D] unknown:0 - Telegram::Client::PendingRpcOperation(0xabc05f68, name = 
"RPC/SetClientDHParams") setFinished(succeeded)
[D] unknown:0 - Telegram::Client::HelpOperation(0xabc7ba68, name = 
"Backend/GetDcConfig") startLater()
[D] unknown:0 - Telegram::Client::ConnectOperation(0xabc72a50, name = 
"ConnectTo(149.154.175.50:443)") setFinished(succeeded)
[D] unknown:0 - deleteLater() Telegram::Client::ConnectOperation(0xabc72a50, name = 
ConnectTo(149.154.175.50:443)")
[D] unknown:0 - Telegram::Client::HelpOperation(0xabc7ba68, name =
 "Backend/GetDcConfig") start()
[C] unknown:0 - quint64 Telegram::Client::RpcLayer::sendRpc(Telegram::Client::
PendingRpcOperation*) First messag
e should be content related!
[D] unknown:0 - deleted() Telegram::PendingOperation(0xa
bc72a50, name = "ConnectTo(149.154.175.50:443)")
[D] unknown:0 - Telegram::Client::BasePendingRpcResult(0
xabc7c3e8, name = "RPC/HelpGetConfig") setFinished(succeeded)
[D] unknown:0 - bool Telegram::Client::BaseRpcLayerExten
sion::processReply(Telegram::Client::PendingRpcOperation
*, TLType*) [with TLType = TLConfig] "Config"
[D] unknown:0 - Telegram::Client::HelpOperation(0xabc7ba
68, name = "Backend/GetDcConfig") setFinished(succeeded)
[D] unknown:0 - Telegram::PendingOperation(0xabc0b400,
name = "ConnectionApi::connectToServer(dcs from settings) ") setFinished(succeeded)
[D] unknown:0 - Telegram::Client::AuthOperation(0xabc711
e0, name = "Auth/StartAuthentication") start()
[D] unknown:0 - Telegram::Client::BasePendingRpcResult(0xabc7e290,
name = "RPC/AuthSendCode") setFinishedWithError(
QHash(("RpcErrorMessage", QVariant(QByteArray,
"PHONE_MIGRATE_4"))("RpcErrorCode", QVariant(int, 303))
("RpcRequestType", QVariant(QString, "AuthSendCode"))) )
[D] unknown:0 - Telegram::Client::BasePendingRpcResult(0
xabc7e290, name = "RPC/AuthSendCode") setFinished(failed)
[D] unknown:0 - deleted() Telegram::PendingOperation(0xabc0b400,
name = "ConnectionApi::connectToServer(dcs from settings)")
Errore di segmentazione
```

**Comment by legacychimera247** [comment]
i have this problem too, maybe it have something to do with the italian number...

**Comment by Kaffeine** [comment]
Better yet (and yet it can be an another issue, will see):

```
[D] void Telegram::Client::ConnectionApiPrivate::setStatus(Telegram::Client::
ConnectionApi::Status, Telegram::Client::ConnectionApi::StatusReason) 
Telegram::Client::ConnectionApi::Status(StatusWaitForConnection) Telegram::
Client::ConnectionApi::StatusReason(StatusReasonLocal)
[D] queueConnectToNextServer interval: 0
[D] Telegram::Client::AuthOperation(0xb9396728, name 
= "Auth/StartAuthentication") runAfter( Telegram::PendingOperation(0xb9395ec0,
 name = "ConnectionApi::connectToServer(dcs from settings)") )
[D] Telegram::Client::AuthOperation(0xb9396728, name 
= "Auth/StartAuthentication") start()
[D] Telegram::PendingOperation* Telegram::Client::AuthOperationPrivate::
requestAuthCode()
[D] Telegram::Client::AuthRpcLayer::PendingAuthSentCode* Telegram::Client::
AuthRpcLayer::sendCode(quint32, const QString&, bool, quint32, const QString&)
 0 "1233544459" false 14617 "e17ac360fd072f83d5d08db45ce9a121"
[D] Telegram::Client::AuthRpcLayer(0xb9171c68) process Telegram::Client::
BasePendingRpcResult(0xb931ea80, name = "RPC/AuthSendCode") 2259611884
[D] Default processing for Telegram::Client::BasePendingRpcResult(0xb931ea80,
 name = "RPC/AuthSendCode") "AuthSendCode"
[W] No connection for processMethod
[W] QObject::connect: invalid null parameter
Segmentation fault
```

**Comment by Kaffeine** [comment]
I did
```
pkcon install telegram-qt-qt5-debuginfo
pkcon install telegram-qt-qt5-declarative-debuginfo
pkcon install gdb

export QT_LOGGING_RULES="telegram.*.debug=true"
gdb jolla-settings

<enter custom phone 123456789>
<crash>
bt
```
and got this:
```
(gdb) bt
#0  QString (other=..., this=0xbeaa11e4) at /usr/include/qt5/QtCore/qstring.h:889
#1  DcOption (this=0xbeaa11e4) at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/TelegramQt/TelegramNamespace.hpp:216
#2  dcOption (this=0x0) at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/TelegramQt/ClientConnection.hpp:21
#3  Telegram::Client::AuthOperationPrivate::requestAuthCode (this=0xb8bb25a8) at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/TelegramQt/Operations/ClientAuthOperation.cpp:166
#4  0xad73e244 in Telegram::PendingOperation::start (this=0xb8c879d0) at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/TelegramQt/PendingOperation.cpp:37
#5  0xad76f4d0 in Telegram::Client::AuthOperation::submitPhoneNumber (this=<optimized out>, phoneNumber=...)
    at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/TelegramQt/Operations/ClientAuthOperation.cpp:245
#6  0xad820cbc in Telegram::Client::DeclarativeAuthOperation::submitPhoneNumber (this=0xb8a65410, phoneNumber=...)
    at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/imports/TelegramQtQml/DeclarativeAuthOperation.cpp:130
#7  0xad823e4e in Telegram::Client::DeclarativeAuthOperation::qt_static_metacall (_o=_o@entry=0xb8a65410, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=18, _a=_a@entry=0xbeaa1370)
    at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/build/imports/TelegramQtQml/moc_DeclarativeAuthOperation.cpp:246
#8  0xad825008 in Telegram::Client::DeclarativeAuthOperation::qt_metacall (this=0xb8a65410, _c=QMetaObject::InvokeMetaMethod, _id=18, _a=0xbeaa1370)
    at /usr/src/debug/telegram-qt-0.2.0+next.staging.20190305182142.1173.gf8cd8a18/build/imports/TelegramQtQml/moc_DeclarativeAuthOperation.cpp:426
#9  0xb689a24c in ?? () from /usr/lib/libQt5Qml.so.5
```

The `#3` shows that for some reason, there is `connection = nullptr` at [ClientAuthOperation.cpp:166](https://github.com/Kaffeine/telegram-qt/blob/3bffa96ea2816135e63b3f1c1cef678df1b58d34/TelegramQt/Operations/ClientAuthOperation.cpp#L166)

**Comment by Kaffeine** [comment]
I think this issue is fixed (in TelegramQt).
